# Generated by Django 2.1.7 on 2019-03-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Review Committee', max_length=1024, null=True, verbose_name='Review Committee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conference.Event', verbose_name='Event')),
            ],
        ),
    ]
