# Generated by Django 2.1.7 on 2019-03-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0002_new_fields_in_proposal_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Proposal', max_length=1024, verbose_name='Title')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposals.Proposal', verbose_name='Event')),
            ],
        ),
    ]
