# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='moderator',
            field=models.CharField(blank=True, help_text='Who will be a moderator of this track.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='room',
            field=models.CharField(blank=True, help_text='In which room the track will take place.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(help_text='A name of a track.', max_length=255),
        ),
    ]
