# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20180219_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='parent_slot',
            field=models.ForeignKey(blank=True, help_text='A slot can be nested inside another slot. If this is the case, connect it here', null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='talk',
            field=models.OneToOneField(blank=True, help_text="If it's a slot for a talk, select your talk here.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.Proposal'),
        ),
    ]
