# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20180219_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='track',
            field=models.ForeignKey(blank=True, help_text='The track to which the slot belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Track'),
        ),
    ]
