# Generated by Django 2.1.5 on 2019-02-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20180225_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='track',
            field=models.ForeignKey(blank=True, help_text='The track to which the slot belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.Track'),
        ),
    ]
