# Generated by Django 2.1.5 on 2019-02-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='year',
        ),
    ]
