# Generated by Django 2.1.5 on 2019-02-04 20:46

import ckeditor.fields
import conference.models.event
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proposals.models.attachment


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('presenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=proposals.models.attachment.unique_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Proposal', max_length=1024)),
                ('state', models.IntegerField(choices=[(0, 'Pending for approval'), (1, 'Approved'), (2, 'Rejected')], default=0, help_text='Current state of proposal')),
                ('type', models.IntegerField(choices=[(0, 'Workshop'), (1, 'Presentation')], help_text='Type of proposal')),
                ('duration', models.IntegerField(help_text='Estimated duration (minutes)')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Short information about proposal')),
                ('extra_info', ckeditor.fields.RichTextField(blank=True, help_text='Extra information', null=True)),
                ('event', models.ForeignKey(blank=True, default=conference.models.event.get_current_event, help_text='Event to which this belongs. e.g. PyCon 2018.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.Event')),
                ('presenter', models.ForeignKey(blank=True, help_text='Foreign key to presenter who proposed this talk/workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenters.Presenter')),
                ('user', models.ForeignKey(blank=True, help_text='Issuer of the proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='proposal',
            field=models.ForeignKey(help_text='Attachment of proposal', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.Proposal'),
        ),
    ]
