# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='', help_text='Title of Proposal', max_length=1024),
            preserve_default=False,
        ),
    ]
