# Generated by Django 2.1.7 on 2019-03-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('proposals', '0002_new_fields_in_proposal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='review_committee',
            field=models.ForeignKey(blank=True, help_text='Committee of the Proposal', null=True, on_delete=django.db.models.deletion.PROTECT, to='committee.Committee', verbose_name='Committee of the Proposal'),
        ),
    ]
