# Generated by Django 2.1.7 on 2019-03-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee_member', '0001_initial'),
        ('proposals', '0002_new_fields_in_proposal_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='committee_member.CommitteeMember', verbose_name='Author')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposals.Proposal', verbose_name='Proposal')),
            ],
        ),
    ]
