# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20180117_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='presenter',
            field=models.ForeignKey(blank=True, help_text='Foreign key to presenter who proposed this talk/workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenters.Presenter'),
        ),
    ]
