# Generated by Django 2.1.7 on 2019-03-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='committee_member.CommitteeMember', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposal', verbose_name='Proposal'),
        ),
    ]
