# Generated by Django 2.1.7 on 2019-03-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee_member', '0002_auto_20190318_1350'),
        ('proposals', '0004_auto_20190318_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Low'), (2, 'Above Low'), (3, 'Average'), (4, 'Above Average'), (5, 'High')], null=True, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='committee_member.CommitteeMember', verbose_name='Author')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.Proposal', verbose_name='Proposal')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
