# Generated by Django 2.1.7 on 2019-04-24 10:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20190419_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, help_text='Proposal/Talk tags', null=True, size=None),
        ),
    ]
