# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Presenter's full name, if presenter is not connected to a user", max_length=200, null=True)),
                ('image', models.ImageField(blank=True, help_text='A photo of a presenter', null=True, upload_to='')),
                ('bio', models.TextField(blank=True, help_text='Short description about the presenter', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='If a presenter is also a user in the system, we connect it that user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
