# Generated by Django 2.1.5 on 2019-02-04 20:46

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(blank=True, help_text='Your twitter handle', max_length=15, null=True)),
                ('github_handle', models.CharField(blank=True, help_text='Your github handle', max_length=39, null=True)),
                ('linkedin_handle', models.CharField(blank=True, help_text='Your linkedin handle', max_length=30, null=True)),
                ('name', models.CharField(blank=True, help_text='Full name to display in the list of speakers', max_length=200, null=True, verbose_name='Full name')),
                ('image', models.ImageField(blank=True, help_text='Your photo', null=True, upload_to='')),
                ('bio', ckeditor.fields.RichTextField(blank=True, help_text='Short description about yourself and your experience with Python', null=True, verbose_name='Short biography')),
                ('expertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, help_text='Your skills and areas of expertise', null=True, size=None)),
                ('active', models.BooleanField(default=False, help_text='If active, it will appear on speakers page')),
                ('event', models.ManyToManyField(blank=True, help_text='Event to which this belongs. e.g. PyCon 2018.', to='conference.Event')),
                ('user', models.OneToOneField(blank=True, help_text='If a presenter is also a user in the system, we connect it that user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
