# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 10:04
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenters', '0004_auto_20180109_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='proposal_data/')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Pending for approval'), (1, 'Approved'), (2, 'Rejected')], default=0, help_text='Current state of proposal')),
                ('type', models.IntegerField(choices=[(0, 'Workshop'), (1, 'Presentation')], help_text='Type of proposal')),
                ('duration', models.IntegerField(help_text='Estimated duration (minutes)')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Short information about proposal')),
                ('extra_info', ckeditor.fields.RichTextField(blank=True, help_text='Extra information', null=True)),
                ('user', models.ForeignKey(help_text='Issuer of the proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='proposal',
            field=models.ForeignKey(help_text='Attachment of proposal', on_delete=django.db.models.deletion.CASCADE, to='presenters.Proposal'),
        ),
    ]
