# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenters', '0005_auto_20180113_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
