# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenters', '0006_auto_20180113_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='user',
            field=models.OneToOneField(blank=True, help_text='If a presenter is also a user in the system, we connect it that user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
