# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenters', '0007_auto_20180123_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='active',
            field=models.BooleanField(default=False, help_text='If active, it will appear on speakers page'),
        ),
    ]
