# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 21:27
from __future__ import unicode_literals

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenters', '0008_presenter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Short description about yourself and your experience with Python', null=True, verbose_name='Short biography'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, help_text='Your skills and areas of expertise', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='github_handle',
            field=models.CharField(blank=True, help_text='Your github handle', max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='image',
            field=models.ImageField(blank=True, help_text='Your photo', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='Your linkedin handle', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='name',
            field=models.CharField(blank=True, help_text='Full name to display in the list of speakers', max_length=200, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your twitter handle', max_length=15, null=True),
        ),
    ]
